// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "SA1505:An opening brace should not be followed by a blank line", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Web.ViewModels.Locations")]
[assembly: SuppressMessage("Build", "SA1210:Using directives should be ordered alphabetically by the namespaces", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Web.ViewModels.Settings")]
[assembly: SuppressMessage("Build", "SA1012:Opening brace should be preceded by a space", Justification = "<AutoGeneratedCode>", Scope = "member", Target = "~P:TAK.Web.ViewModels.Locations.LocationDeleteViewModel.Id")]
