// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "SA1200:Using directive should appear within a namespace declaration", Justification = "<AutoGeneratedCode>")]
[assembly: SuppressMessage("Build", "SA1122:Use string.Empty for empty strings", Justification = "<AutoGeneratedCode>", Scope = "member", Target = "~M:TAK.Data.Migrations.AddLatinNameProp.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Build", "SA1122:Use string.Empty for empty strings", Justification = "<AutoGeneratedCode>", Scope = "member", Target = "~M:TAK.Data.Migrations.AddLatinTitleProp.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Build", "SA1122:Use string.Empty for empty strings", Justification = "<AutoGeneratedCode>", Scope = "member", Target = "~M:TAK.Data.Migrations.AddLocationProps.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Build", "SA1210:Using directives should be ordered alphabetically by the namespaces", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Data")]
[assembly: SuppressMessage("Build", "SA1518:File is required to end with a single newline character", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Data.CloudinaryHelper")]
[assembly: SuppressMessage("Build", "SA1210:Using directives should be ordered alphabetically by the namespaces", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Data.Configurations")]
[assembly: SuppressMessage("Build", "SA1210:Using directives should be ordered alphabetically by the namespaces", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Data.Repositories")]
[assembly: SuppressMessage("Build", "SA1210:Using directives should be ordered alphabetically by the namespaces", Justification = "<AutoGeneratedCode>", Scope = "namespace", Target = "~N:TAK.Data.Seeding")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<BreakingFunctionality>", Scope = "member", Target = "~M:TAK.Data.CloudinaryHelper.CloudinaryExtension.UploadMultipleAsync(CloudinaryDotNet.Cloudinary,System.Collections.Generic.ICollection{Microsoft.AspNetCore.Http.IFormFile})~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
